dist: trusty
sudo: required

language: python
python:
  - "3.5.1"

services:
  - mysql

before_install:
    - "export DISPLAY=:99.0"                         
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

branches:
  only:
    - develop

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 survey
  - mysql -e 'create database edc character set utf8;'
  - python manage.py makemigrations
  - python manage.py migrate

script: 
  - coverage run --source=survey manage.py test

after_success:
  - coveralls
